<?php

use simpleserv\webfilesframework\core\datastore\MDatastoreFactory;
use simpleserv\webfilesframework\core\datastore\types\database\MDatabaseDatastore;
use simpleserv\webfilesframework\core\datasystem\database\MDatabaseConnection;
use simpleserv\webfilesframework\core\datasystem\file\format\MWebfile;

/**
 * Test class for MDatabaseDatastore.
 * Generated by PHPUnit on 2015-04-11 at 17:49:50.
 */
class MDatabaseDatastoreTest extends PHPUnit_Framework_TestCase {
    /**
     * @var MDatastoreFactory
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
    	
    	$connection = new MDatabaseConnection();
    	$stub = $this
    			->getMock('simpleserv\webfilesframework\core\datasystem\database\MDatabaseConnection');
    	
    	$invocationMocker = $stub->__phpunit_getInvocationMocker();//('query')->willReturn(null);
    	
        $this->object = new MDatabaseDatastore($stub);
        //$this->object->tryConnect();
        
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
    }

    /**
     * @covers simpleserv\webfilesframework\core\datastore\types\database\MDatabaseDatastore::
     */
    public function testGetByTemplate() {
        
    	$template = new MWebfile();
    	//$this->object->getByTemplate($template);
    }
}
